export const ROLES = {
    MEMBER: 'MEMBER',
    POLLING_UNIT_LEAD: 'POLLING_UNIT_LEAD',
    WARD_COORDINATOR: 'WARD_COORDINATOR',
    LGA_COORDINATOR: 'LGA_COORDINATOR',
    STATE_COORDINATOR: 'STATE_COORDINATOR',
    ADMIN: 'ADMIN',
} as const;

export type Role = keyof typeof ROLES;
